version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"

  ngrok:
    image: ngrok/ngrok:latest
    command: http web:80
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "2wgermMWaGofsSOmhyN0wP6tugf_3N3ehGg6EWPffS8o1WPdQ"
    depends_on:
      - web
